name: Main Github Actions
on:
  push:
    branches: [ master, main ]
  # pull_request:
  #   branches: [ master ]

jobs:
  Run_test:
    runs-on: ubuntu-20.04 # Choosing OS
    strategy:
      matrix:
        node-version: [17.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # trying to install npm packages
    - run: npm i -g npm@latest
    - run: npm i npm@latest
    - run: npm i
    - name: run test
      # trying to run tests
      run: npm run test:headless
    - name: Create Report
      if: always()
      trying to save history of previous runs if it is exists
      run: cp -r $(pwd)/allure-report/history/. $(pwd)/allure-results/history || true && npm run allure:generate
    - name: Upload artifact allure-report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-report
        path: ./allure-report
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./allure-report
      # If your repo is private and you want upload your report to another repo uncomment and set credential 
    # - name: Pushes to another repository
    #   uses: cpina/github-action-push-to-another-repository@main
    #   if: always()
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
    #   with:
    #     source-directory: 'docs'
    #     destination-github-username: 'UserName'
    #     destination-repository-name: 'RepoName'
    #     user-email: some.email@gmail.com
    #     target-branch: main