name: Main Github Actions
on:
  workflow_dispatch:
push:
  branches:
    - 'main' # (main branch) Set branch of the GH repo to push      
jobs:
  test_suite: # Name of the job
  runs-on: ubuntu-20.04 # Choosing OS
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
   # with:
      #node-version: 17; # In command line run “node -v” and choose your version
- run: npm ci
# - run: npm config set script-shell &quot;C:\Program Files\Git\bin\bash.exe&quot;
- name: run test
  run: npm run test:headless # Our name of the headless script
- name: Copy History
  if: always()
  run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
- name: Generate Report
  if: always()
  run: npm run allure:generate # Name of the allure generate script
- name: Upload Results
  uses: actions/upload-artifact@v1
  if: always()
  with:
    name: allure-results
    path: ./allure-results # Name of the folder with allure results
- name: Publishing Allure artifact to Github Actions
  uses: actions/upload-artifact@v2
  if: always()
  with:
  name: allure-report
  path: allure-report
- name: Deploy report
  uses: JamesIves/github-pages-deploy-action@4.1.4
  if: always()
with: 
  branch: gh-pages # The branch the action should deploy to.
  folder: allure-report # The folder the action should deploy.
      # If your repo is private and you want upload your report to another repo uncomment and set credential 
    # - name: Pushes to another repository
    #   uses: cpina/github-action-push-to-another-repository@main
    #   if: always()
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
    #   with:
    #     source-directory: 'docs'
    #     destination-github-username: 'UserName'
    #     destination-repository-name: 'RepoName'
    #     user-email: some.email@gmail.com
    #     target-branch: main